import langchain_pine_scratch as lch
import streamlit as st

#st.image('images/bhimrao.jpg', width = 300)
st.title('Relevant Bhimrao Project')


query = st.text_area(label = 'What do you want to know about Writing and Speeches of Babasaheb or Constitution of India?', max_chars=400)
if query:
    path = 'volumes'
    db = lch.create_vectordb(path)
    response = lch.get_response_from_query(db, query)
    st.write(response)
    st.write('--------------------------------------------')
    st.write('Response is generated by AI module trained on 17 volumes of Writing and Speeches of Babasaheb Ambedkar \n')
    st.write('Initiative by KNEWRA.ORG -- AI Knowledge Project -- \n')
    st.write("Know more about us [HERE](https://knewra.medium.com)")





